import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#030712] text-white font-sans">
      <nav className="border-b border-gray-800">
        <div className="max-w-3xl mx-auto px-6 py-4">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-orange-500 to-red-600 flex items-center justify-center text-xs font-extrabold">
              B
            </div>
            <span className="text-lg font-bold">Brikk</span>
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-12">
        <h1 className="text-3xl font-extrabold mb-2">Terms of Service</h1>
        <p className="text-gray-500 text-sm mb-8">Last updated: March 21, 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Brikk (&quot;the Service&quot;), operated by Be Cause Partners Pte Ltd
              (&quot;we,&quot; &quot;us,&quot; &quot;our&quot;), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">2. Description of Service</h2>
            <p>
              Brikk is an AI-powered triathlon coaching platform that connects to your Garmin device
              to provide personalized training analysis, race projections, and coaching recommendations.
              The Service is available at brikk.run.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">3. Account Registration</h2>
            <p>
              You must create an account to use the Service. You are responsible for maintaining the
              security of your account credentials and for all activity under your account. You must
              provide accurate information and update it if it changes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">4. Garmin Integration</h2>
            <p>
              By connecting your Garmin account, you authorize Brikk to access your health and training
              data through Garmin&apos;s official APIs. You can revoke this access at any time through your
              Garmin account settings or by disconnecting within Brikk.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">5. Not Medical Advice</h2>
            <p>
              <strong className="text-orange-400">Brikk is not a medical service.</strong> The coaching,
              analysis, and recommendations provided are for informational and training purposes only.
              They do not constitute medical advice, diagnosis, or treatment. Always consult a qualified
              healthcare professional before making changes to your training, nutrition, or health
              practices. If you experience pain, injury, or health concerns, seek medical attention
              immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">6. AI-Generated Content</h2>
            <p>
              Brikk&apos;s coaching responses are generated by artificial intelligence (Anthropic&apos;s Claude).
              While we strive for accuracy, AI-generated content may contain errors or inaccuracies.
              You should use your own judgment and experience when following any training recommendations.
              We are not liable for any injury, loss, or damage resulting from following AI-generated advice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">7. Acceptable Use</h2>
            <p>
              You agree not to: use the Service for any unlawful purpose, attempt to gain unauthorized
              access to our systems, interfere with other users&apos; use of the Service, submit false or
              misleading information, or reverse-engineer any part of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">8. Intellectual Property</h2>
            <p>
              The Brikk name, logo, and Service design are the property of Be Cause Partners Pte Ltd.
              Your training data remains yours — we claim no ownership over your personal data or
              Garmin data.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">9. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Brikk and Be Cause Partners Pte Ltd shall not
              be liable for any indirect, incidental, special, consequential, or punitive damages
              arising from your use of the Service. Our total liability shall not exceed the amount
              you have paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">10. Service Availability</h2>
            <p>
              We strive to maintain high availability but do not guarantee uninterrupted access.
              The Service may be temporarily unavailable for maintenance, updates, or due to
              circumstances beyond our control.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">11. Termination</h2>
            <p>
              You may stop using the Service at any time. We may suspend or terminate your account
              if you violate these terms. Upon termination, your right to use the Service ceases
              immediately.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">12. Changes to Terms</h2>
            <p>
              We may update these terms from time to time. We will notify you of significant changes
              by email or through the Service. Continued use after changes constitutes acceptance
              of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">13. Governing Law</h2>
            <p>
              These terms are governed by the laws of Singapore. Any disputes shall be resolved
              in the courts of Singapore.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-white mt-8 mb-3">14. Contact</h2>
            <p>
              Questions about these terms? Contact us at:{" "}
              <a href="mailto:coach@brikk.run" className="text-orange-400 hover:underline">
                coach@brikk.run
              </a>
            </p>
            <p className="mt-2">
              Be Cause Partners Pte Ltd<br />
              Singapore
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
