import Link from "next/link";

export default function Terms() {
  return (
    <div className="min-h-screen bg-[#030712] text-white font-sans">
      <nav className="max-w-4xl mx-auto px-6 py-6">
        <Link href="/" className="flex items-center gap-3 w-fit">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center text-sm font-extrabold">
            IC
          </div>
          <span className="text-xl font-bold tracking-tight">Coach IronClaw</span>
        </Link>
      </nav>
      <article className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-gray-500 mb-12">Last updated: March 19, 2026</p>

        <div className="prose prose-invert prose-gray max-w-none space-y-8 text-gray-300 leading-relaxed">
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Coach IronClaw (&quot;the Service&quot;), operated by Be Cause Partners Pte Ltd, 
              you agree to be bound by these Terms of Service. If you do not agree to these terms, 
              do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>
              Coach IronClaw is an AI-powered triathlon coaching platform that provides personalized 
              training analysis, training plans, race projections, and coaching recommendations based 
              on data synced from your Garmin device. The Service is intended for informational and 
              educational purposes related to endurance sports training.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Not Medical Advice</h2>
            <p>
              Coach IronClaw is not a medical service. The training recommendations, health metric 
              analysis, and coaching advice provided by the platform are generated by AI and are not 
              a substitute for professional medical advice, diagnosis, or treatment. Always consult 
              a qualified healthcare provider before starting or modifying any exercise program, 
              especially if you have pre-existing health conditions. If you experience pain, dizziness, 
              or other concerning symptoms during training, stop immediately and seek medical attention.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Account Responsibilities</h2>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and 
              for all activities that occur under your account. You must provide accurate and complete 
              information when creating your account. You agree to notify us immediately of any 
              unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Garmin Data Integration</h2>
            <p>
              By connecting your Garmin account, you authorize Coach IronClaw to access your fitness 
              and health data through the Garmin Health API. You may revoke this access at any time 
              through your Garmin Connect settings or by disconnecting within Coach IronClaw. We are 
              not affiliated with or endorsed by Garmin Ltd. or its subsidiaries.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. AI-Generated Content</h2>
            <p>
              Coaching recommendations, training plans, and race projections are generated by artificial 
              intelligence. While we strive for accuracy, AI-generated content may contain errors or 
              inaccuracies. You should use your own judgment and experience when following any training 
              advice. Coach IronClaw is not liable for injuries, losses, or damages resulting from 
              following AI-generated coaching recommendations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Acceptable Use</h2>
            <p>
              You agree not to: use the Service for any unlawful purpose; attempt to gain unauthorized 
              access to any part of the Service; interfere with or disrupt the Service; reverse engineer 
              or attempt to extract source code from the Service; or use the Service to develop a 
              competing product.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Intellectual Property</h2>
            <p>
              The Service, including its design, features, and content, is owned by Be Cause Partners Pte Ltd. 
              Your training data remains yours. You retain all rights to your personal fitness and health 
              data. By using the Service, you grant us a limited license to process your data solely for 
              the purpose of providing coaching services to you.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Service Availability</h2>
            <p>
              We aim to provide reliable service but do not guarantee uninterrupted access. The Service 
              may be temporarily unavailable due to maintenance, updates, or circumstances beyond our 
              control. We reserve the right to modify, suspend, or discontinue any aspect of the 
              Service at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, Be Cause Partners Pte Ltd and its officers, 
              directors, and employees shall not be liable for any indirect, incidental, special, 
              consequential, or punitive damages arising from your use of the Service, including 
              but not limited to physical injury, loss of data, or loss of profits.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Termination</h2>
            <p>
              You may terminate your account at any time by contacting us. We may terminate or suspend 
              your access to the Service at our discretion, with or without cause. Upon termination, 
              your right to use the Service ceases immediately. We will delete your data within 30 days 
              of account termination unless required by law to retain it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">12. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of Singapore. 
              Any disputes arising from these Terms or the Service shall be subject to the exclusive 
              jurisdiction of the courts of Singapore.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">13. Changes to Terms</h2>
            <p>
              We reserve the right to update these Terms at any time. We will notify you of material 
              changes via email or through the platform. Continued use of the Service after changes 
              constitutes acceptance of the updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">14. Contact</h2>
            <p>
              For questions about these Terms, contact us at:{" "}
              <a href="mailto:hawkins@hawkinspham.com" className="text-blue-400 hover:text-blue-300">
                hawkins@hawkinspham.com
              </a>
            </p>
          </section>
        </div>
      </article>
    </div>
  );
}